export enum Platform {
  LINKEDIN = 'LinkedIn',
  PINTEREST = 'Pinterest',
  INSTAGRAM = 'Instagram',
  FACEBOOK = 'Facebook',
  THREADS = 'Threads'
}

export enum Tone {
  PROFESSIONAL = 'Professional',
  CASUAL = 'Casual',
  WITTY = 'Witty',
  CONTROVERSIAL = 'Controversial',
  EDUCATIONAL = 'Educational',
  INSPIRATIONAL = 'Inspirational'
}

export enum Length {
  SHORT = 'Short',
  MEDIUM = 'Medium',
  LONG = 'Long'
}

export enum AspectRatio {
  RATIO_1_1 = '1:1',
  RATIO_3_4 = '3:4',
  RATIO_4_5 = '4:5',
  RATIO_16_9 = '16:9',
  RATIO_9_16 = '9:16'
}

export interface GenerationConfig {
  topic: string;
  platform: Platform;
  tone: Tone;
  length: Length;
  aspectRatio: AspectRatio;
  includeHashtags: boolean;
  includeEmoji: boolean;
}

export interface GeneratedPost {
  id: string;
  content: string;
  imagePrompt?: string; // Optional image prompt generated by AI
  generatedImageUrl?: string; // Optional generated image URL
  timestamp: number;
  config: GenerationConfig;
}

export type GenerationStatus = 'idle' | 'generating_text' | 'generating_image' | 'complete' | 'error';